# Cross Validation

#### K-Fold cross validation

In [59]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold

x = np.array([[1,2],[2,3],[3,4],[4,5]])
y = np.array([0,1,0,1])

In [60]:
"""x = np.array([[1,2],[2,3],[3,4],[4,5]])
y = np.array([[1,2,3,4]])
data = np.concatenate((x,y.T),axis = 1)
pd.DataFrame(data)"""

'x = np.array([[1,2],[2,3],[3,4],[4,5]])\ny = np.array([[1,2,3,4]])\ndata = np.concatenate((x,y.T),axis = 1)\npd.DataFrame(data)'

In [71]:
kf = KFold(n_splits = 2,shuffle = True)
kf.get_n_splits(x)

2

In [72]:
for train_index,test_index in kf.split(x,y):
    print(train_index,test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

[0 2] [1 3]
[1 3] [0 2]


#### Stratified KFold cross validation

In [73]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits = 2,shuffle = True)


In [74]:
for train_index,test_index in skf.split(x,y):
    print(train_index,test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

[0 3] [1 2]
[1 2] [0 3]


#### Time Series cross validation

In [77]:
from sklearn.model_selection import TimeSeriesSplit

x = np.array([[1,2],[3,2],[4,5],[8,7],[3,9],[7,2]])
y = np.array([1,2,3,4,5,6])

tss = TimeSeriesSplit(n_splits = 3, max_train_size = None)

In [86]:
for train,test in tss.split(x,y):
    print('%s  %s'%(train,test))

[0 1 2]  [3]
[0 1 2 3]  [4]
[0 1 2 3 4]  [5]
