# Cross Validation

- Bootstrap method

- Holdout method

- Leave-one-out cross validation and (p-out)
 
- K-fold cross validation

- Stratified cross validation

- Time-series cross validation


#### Bootstrap method :

In [8]:
from sklearn.utils import resample


In [9]:
data = [1,2,3,4,5,6,7,8,9]

In [35]:
boot_resample = resample(data,replace = False,n_samples = 6,random_state=2)

print('bootstrap_resample : %s'%boot_resample) #used for training

result = [x for x in data if x not in boot_resample]

print('oob : %s'%result) #used for testing

bootstrap_resample : [5, 2, 7, 3, 4, 1]
oob : [6, 8, 9]


#### Holdout method :

In [37]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [43]:
iris = datasets.load_iris()
iris.data.shape,iris.target.shape

(150,)

In [46]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.4,random_state = 0)

x_train.shape,x_test.shape

((90, 4), (60, 4))

In [47]:
y_train.shape,y_test.shape

((90,), (60,))

In [50]:
svmclsf = svm.SVC(kernel = "linear",C = 1).fit(x_train,y_train)

svmclsf.score(x_test,y_test)

0.9666666666666667

#### LeaveOneOut & p-out method :

In [78]:
from sklearn.model_selection import LeaveOneOut,LeavePOut

x = [[1,0],[0,0],[5,3],[3,6],[8,4],[3,5]]
y = [6,3,2,5,7,1]

In [79]:
loo = LeaveOneOut().split(x)
loo

<generator object BaseCrossValidator.split at 0x000000000F10C6D0>

In [80]:
for train_index,test_index in loo:
    print(train_index,test_index)

[1 2 3 4 5] [0]
[0 2 3 4 5] [1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]


In [82]:
lpo = LeavePOut(p = 2).split(x)

In [83]:
for train_index,test_index in lpo:
    print(train_index,test_index)

[2 3 4 5] [0 1]
[1 3 4 5] [0 2]
[1 2 4 5] [0 3]
[1 2 3 5] [0 4]
[1 2 3 4] [0 5]
[0 3 4 5] [1 2]
[0 2 4 5] [1 3]
[0 2 3 5] [1 4]
[0 2 3 4] [1 5]
[0 1 4 5] [2 3]
[0 1 3 5] [2 4]
[0 1 3 4] [2 5]
[0 1 2 5] [3 4]
[0 1 2 4] [3 5]
[0 1 2 3] [4 5]
